@startuml 时序图
title
时序图-入门
end title
== 说明 ==
human -> AI : request
AI -> human : response
AI -> 分布式计算系统 : 转交
AI <- 分布式计算系统 : 返回
== 数据上传 == 
human -> AI : 上传数据、
note left: 我正在上传数据

AI --> 分布式计算系统 : 转交数据
... 不超过5分钟 ...
分布式计算系统 --> AI : 状态返回

note right : 状态返回

AI -> human : 状态返回
== 状态显示 ==
human -> human : 给自己发消息 

@enduml

~ 使用说明
~
使用 title 来指定标题
'->' 和 '-->' 来指示线条的形式
在每个时序后面加冒号 : 来添加注释
使用 note 来显示备注，备注可以指定显示在左边或右边
使用 == xxx == 来分隔时序图
使用 ... 来表示延迟省略号
节点可以给自己发送消息，方法是发送方和接收方使用同一个主体即可


作者：kamidox
链接：https://www.jianshu.com/p/e92a52770832
來源：简书
简书著作权归作者所有，任何形式的转载都请联系作者获得授权并注明出处。
~