//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarsiLibrary.FX.Win.Resources {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public sealed class Strings {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        private Strings() {
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FarsiLibrary.FX.Win.Resources.Strings", typeof(Strings).Assembly);
                    _resourceManager = temp;
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '[Date is Null]'.
        /// </summary>
        public static string DatePicker_NullText {
            get {
                return ResourceManager.GetString("DatePicker_NullText", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Empty'.
        /// </summary>
        public static string MonthView_EmptyButton {
            get {
                return ResourceManager.GetString("MonthView_EmptyButton", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Today'.
        /// </summary>
        public static string MonthView_TodayButton {
            get {
                return ResourceManager.GetString("MonthView_TodayButton", _resourceCulture);
            }
        }
    }
}
